"""A readable, pure-Python NMOS 6502 instruction core, correct to the bus cycle."""

from sixfiveohtwo.console import CommandDebugger, CommandError, CommandResult
from sixfiveohtwo.cpu import (
    FLAG_B,
    FLAG_C,
    FLAG_D,
    FLAG_I,
    FLAG_N,
    FLAG_U,
    FLAG_V,
    FLAG_Z,
    MOS6502,
)
from sixfiveohtwo.debug import (
    Access,
    BoundaryKind,
    DebugSession,
    DebugTarget,
    RunResult,
    StepRecord,
    StopReason,
    next_boundary,
)
from sixfiveohtwo.disasm import (
    ByteReader,
    Instruction,
    disassemble,
    disassemble_bytes,
    disassemble_range,
)
from sixfiveohtwo.state import CPUState
from sixfiveohtwo.trace import (
    TRACE_SCHEMA_VERSION,
    TraceDifference,
    TraceDivergence,
    TraceValue,
    compare_step_records,
    first_session_divergence,
    first_trace_divergence,
    iter_session_steps,
    iter_trace_divergences,
    read_trace,
    step_record_from_dict,
    step_record_to_dict,
    write_trace,
)

__all__ = [
    "FLAG_B",
    "FLAG_C",
    "FLAG_D",
    "FLAG_I",
    "FLAG_N",
    "FLAG_U",
    "FLAG_V",
    "FLAG_Z",
    "MOS6502",
    "TRACE_SCHEMA_VERSION",
    "Access",
    "BoundaryKind",
    "ByteReader",
    "CPUState",
    "CommandDebugger",
    "CommandError",
    "CommandResult",
    "DebugSession",
    "DebugTarget",
    "Instruction",
    "RunResult",
    "StepRecord",
    "StopReason",
    "TraceDifference",
    "TraceDivergence",
    "TraceValue",
    "compare_step_records",
    "disassemble",
    "disassemble_bytes",
    "disassemble_range",
    "first_session_divergence",
    "first_trace_divergence",
    "iter_session_steps",
    "iter_trace_divergences",
    "next_boundary",
    "read_trace",
    "step_record_from_dict",
    "step_record_to_dict",
    "write_trace",
]
