"""The opcode map: which handler, addressing mode and base cycle count each opcode has.

``OPCODES`` below is all 256 opcodes, one line each: handler, addressing mode,
cycles. The documented 151 are PM Appendix B's (pp. B-3 to B-29) and its
Appendix C timing table (p. C-1); the other 105 are NMS's opcode matrix (p. 1).
Both are checked opcode by opcode against the SingleStepTests corpus.

The cycle count is the base: an indexed read that crosses a page adds one
(``abx``, ``aby``, ``izy``), and a taken branch adds one, or two across a
page. Stores and read-modify-writes spend that cycle always, so their modes
(``abx_w``, ``aby_w``, ``izy_w``) cost the same whatever the index.

Addressing modes: ``imm`` immediate, ``zp`` zero page, ``zpx``/``zpy`` zero
page indexed, ``abs`` absolute, ``abx``/``aby`` absolute indexed, ``izx``
(zp,X), ``izy`` (zp),Y. ``None`` means the handler makes its own bus cycles:
implied, accumulator, relative, the stack, JMP, JSR and BRK.

Dispatch is an explicit 256-entry table, built once per class, so that
``step()`` is one list index and one call -- the shape PyPy compiles well.
"""

from collections.abc import Callable

#: opcode: (handler, addressing mode, base cycles)
OPCODES: dict[int, tuple[str, str | None, int]] = {
    0x00: ("brk", None, 7),
    0x01: ("ora", "izx", 6),
    0x02: ("jam", None, 11),
    0x03: ("slo", "izx", 8),
    0x04: ("nop_read", "zp", 3),
    0x05: ("ora", "zp", 3),
    0x06: ("asl", "zp", 5),
    0x07: ("slo", "zp", 5),
    0x08: ("php", None, 3),
    0x09: ("ora", "imm", 2),
    0x0A: ("asl_a", None, 2),
    0x0B: ("anc", "imm", 2),
    0x0C: ("nop_read", "abs", 4),
    0x0D: ("ora", "abs", 4),
    0x0E: ("asl", "abs", 6),
    0x0F: ("slo", "abs", 6),
    0x10: ("bpl", None, 2),
    0x11: ("ora", "izy", 5),
    0x12: ("jam", None, 11),
    0x13: ("slo", "izy_w", 8),
    0x14: ("nop_read", "zpx", 4),
    0x15: ("ora", "zpx", 4),
    0x16: ("asl", "zpx", 6),
    0x17: ("slo", "zpx", 6),
    0x18: ("clc", None, 2),
    0x19: ("ora", "aby", 4),
    0x1A: ("nop", None, 2),
    0x1B: ("slo", "aby_w", 7),
    0x1C: ("nop_read", "abx", 4),
    0x1D: ("ora", "abx", 4),
    0x1E: ("asl", "abx_w", 7),
    0x1F: ("slo", "abx_w", 7),
    0x20: ("jsr", None, 6),
    0x21: ("and", "izx", 6),
    0x22: ("jam", None, 11),
    0x23: ("rla", "izx", 8),
    0x24: ("bit", "zp", 3),
    0x25: ("and", "zp", 3),
    0x26: ("rol", "zp", 5),
    0x27: ("rla", "zp", 5),
    0x28: ("plp", None, 4),
    0x29: ("and", "imm", 2),
    0x2A: ("rol_a", None, 2),
    0x2B: ("anc", "imm", 2),
    0x2C: ("bit", "abs", 4),
    0x2D: ("and", "abs", 4),
    0x2E: ("rol", "abs", 6),
    0x2F: ("rla", "abs", 6),
    0x30: ("bmi", None, 2),
    0x31: ("and", "izy", 5),
    0x32: ("jam", None, 11),
    0x33: ("rla", "izy_w", 8),
    0x34: ("nop_read", "zpx", 4),
    0x35: ("and", "zpx", 4),
    0x36: ("rol", "zpx", 6),
    0x37: ("rla", "zpx", 6),
    0x38: ("sec", None, 2),
    0x39: ("and", "aby", 4),
    0x3A: ("nop", None, 2),
    0x3B: ("rla", "aby_w", 7),
    0x3C: ("nop_read", "abx", 4),
    0x3D: ("and", "abx", 4),
    0x3E: ("rol", "abx_w", 7),
    0x3F: ("rla", "abx_w", 7),
    0x40: ("rti", None, 6),
    0x41: ("eor", "izx", 6),
    0x42: ("jam", None, 11),
    0x43: ("sre", "izx", 8),
    0x44: ("nop_read", "zp", 3),
    0x45: ("eor", "zp", 3),
    0x46: ("lsr", "zp", 5),
    0x47: ("sre", "zp", 5),
    0x48: ("pha", None, 3),
    0x49: ("eor", "imm", 2),
    0x4A: ("lsr_a", None, 2),
    0x4B: ("alr", "imm", 2),
    0x4C: ("jmp", None, 3),
    0x4D: ("eor", "abs", 4),
    0x4E: ("lsr", "abs", 6),
    0x4F: ("sre", "abs", 6),
    0x50: ("bvc", None, 2),
    0x51: ("eor", "izy", 5),
    0x52: ("jam", None, 11),
    0x53: ("sre", "izy_w", 8),
    0x54: ("nop_read", "zpx", 4),
    0x55: ("eor", "zpx", 4),
    0x56: ("lsr", "zpx", 6),
    0x57: ("sre", "zpx", 6),
    0x58: ("cli", None, 2),
    0x59: ("eor", "aby", 4),
    0x5A: ("nop", None, 2),
    0x5B: ("sre", "aby_w", 7),
    0x5C: ("nop_read", "abx", 4),
    0x5D: ("eor", "abx", 4),
    0x5E: ("lsr", "abx_w", 7),
    0x5F: ("sre", "abx_w", 7),
    0x60: ("rts", None, 6),
    0x61: ("adc", "izx", 6),
    0x62: ("jam", None, 11),
    0x63: ("rra", "izx", 8),
    0x64: ("nop_read", "zp", 3),
    0x65: ("adc", "zp", 3),
    0x66: ("ror", "zp", 5),
    0x67: ("rra", "zp", 5),
    0x68: ("pla", None, 4),
    0x69: ("adc", "imm", 2),
    0x6A: ("ror_a", None, 2),
    0x6B: ("arr", "imm", 2),
    0x6C: ("jmp_ind", None, 5),
    0x6D: ("adc", "abs", 4),
    0x6E: ("ror", "abs", 6),
    0x6F: ("rra", "abs", 6),
    0x70: ("bvs", None, 2),
    0x71: ("adc", "izy", 5),
    0x72: ("jam", None, 11),
    0x73: ("rra", "izy_w", 8),
    0x74: ("nop_read", "zpx", 4),
    0x75: ("adc", "zpx", 4),
    0x76: ("ror", "zpx", 6),
    0x77: ("rra", "zpx", 6),
    0x78: ("sei", None, 2),
    0x79: ("adc", "aby", 4),
    0x7A: ("nop", None, 2),
    0x7B: ("rra", "aby_w", 7),
    0x7C: ("nop_read", "abx", 4),
    0x7D: ("adc", "abx", 4),
    0x7E: ("ror", "abx_w", 7),
    0x7F: ("rra", "abx_w", 7),
    0x80: ("nop_read", "imm", 2),
    0x81: ("sta", "izx", 6),
    0x82: ("nop_read", "imm", 2),
    0x83: ("sax", "izx", 6),
    0x84: ("sty", "zp", 3),
    0x85: ("sta", "zp", 3),
    0x86: ("stx", "zp", 3),
    0x87: ("sax", "zp", 3),
    0x88: ("dey", None, 2),
    0x89: ("nop_read", "imm", 2),
    0x8A: ("txa", None, 2),
    0x8B: ("ane", "imm", 2),
    0x8C: ("sty", "abs", 4),
    0x8D: ("sta", "abs", 4),
    0x8E: ("stx", "abs", 4),
    0x8F: ("sax", "abs", 4),
    0x90: ("bcc", None, 2),
    0x91: ("sta", "izy_w", 6),
    0x92: ("jam", None, 11),
    0x93: ("sha", "izy_w", 6),
    0x94: ("sty", "zpx", 4),
    0x95: ("sta", "zpx", 4),
    0x96: ("stx", "zpy", 4),
    0x97: ("sax", "zpy", 4),
    0x98: ("tya", None, 2),
    0x99: ("sta", "aby_w", 5),
    0x9A: ("txs", None, 2),
    0x9B: ("tas", "aby_w", 5),
    0x9C: ("shy", "abx_w", 5),
    0x9D: ("sta", "abx_w", 5),
    0x9E: ("shx", "aby_w", 5),
    0x9F: ("sha", "aby_w", 5),
    0xA0: ("ldy", "imm", 2),
    0xA1: ("lda", "izx", 6),
    0xA2: ("ldx", "imm", 2),
    0xA3: ("lax", "izx", 6),
    0xA4: ("ldy", "zp", 3),
    0xA5: ("lda", "zp", 3),
    0xA6: ("ldx", "zp", 3),
    0xA7: ("lax", "zp", 3),
    0xA8: ("tay", None, 2),
    0xA9: ("lda", "imm", 2),
    0xAA: ("tax", None, 2),
    0xAB: ("lxa", "imm", 2),
    0xAC: ("ldy", "abs", 4),
    0xAD: ("lda", "abs", 4),
    0xAE: ("ldx", "abs", 4),
    0xAF: ("lax", "abs", 4),
    0xB0: ("bcs", None, 2),
    0xB1: ("lda", "izy", 5),
    0xB2: ("jam", None, 11),
    0xB3: ("lax", "izy", 5),
    0xB4: ("ldy", "zpx", 4),
    0xB5: ("lda", "zpx", 4),
    0xB6: ("ldx", "zpy", 4),
    0xB7: ("lax", "zpy", 4),
    0xB8: ("clv", None, 2),
    0xB9: ("lda", "aby", 4),
    0xBA: ("tsx", None, 2),
    0xBB: ("las", "aby", 4),
    0xBC: ("ldy", "abx", 4),
    0xBD: ("lda", "abx", 4),
    0xBE: ("ldx", "aby", 4),
    0xBF: ("lax", "aby", 4),
    0xC0: ("cpy", "imm", 2),
    0xC1: ("cmp", "izx", 6),
    0xC2: ("nop_read", "imm", 2),
    0xC3: ("dcp", "izx", 8),
    0xC4: ("cpy", "zp", 3),
    0xC5: ("cmp", "zp", 3),
    0xC6: ("dec", "zp", 5),
    0xC7: ("dcp", "zp", 5),
    0xC8: ("iny", None, 2),
    0xC9: ("cmp", "imm", 2),
    0xCA: ("dex", None, 2),
    0xCB: ("sbx", "imm", 2),
    0xCC: ("cpy", "abs", 4),
    0xCD: ("cmp", "abs", 4),
    0xCE: ("dec", "abs", 6),
    0xCF: ("dcp", "abs", 6),
    0xD0: ("bne", None, 2),
    0xD1: ("cmp", "izy", 5),
    0xD2: ("jam", None, 11),
    0xD3: ("dcp", "izy_w", 8),
    0xD4: ("nop_read", "zpx", 4),
    0xD5: ("cmp", "zpx", 4),
    0xD6: ("dec", "zpx", 6),
    0xD7: ("dcp", "zpx", 6),
    0xD8: ("cld", None, 2),
    0xD9: ("cmp", "aby", 4),
    0xDA: ("nop", None, 2),
    0xDB: ("dcp", "aby_w", 7),
    0xDC: ("nop_read", "abx", 4),
    0xDD: ("cmp", "abx", 4),
    0xDE: ("dec", "abx_w", 7),
    0xDF: ("dcp", "abx_w", 7),
    0xE0: ("cpx", "imm", 2),
    0xE1: ("sbc", "izx", 6),
    0xE2: ("nop_read", "imm", 2),
    0xE3: ("isc", "izx", 8),
    0xE4: ("cpx", "zp", 3),
    0xE5: ("sbc", "zp", 3),
    0xE6: ("inc", "zp", 5),
    0xE7: ("isc", "zp", 5),
    0xE8: ("inx", None, 2),
    0xE9: ("sbc", "imm", 2),
    0xEA: ("nop", None, 2),
    0xEB: ("usbc", "imm", 2),
    0xEC: ("cpx", "abs", 4),
    0xED: ("sbc", "abs", 4),
    0xEE: ("inc", "abs", 6),
    0xEF: ("isc", "abs", 6),
    0xF0: ("beq", None, 2),
    0xF1: ("sbc", "izy", 5),
    0xF2: ("jam", None, 11),
    0xF3: ("isc", "izy_w", 8),
    0xF4: ("nop_read", "zpx", 4),
    0xF5: ("sbc", "zpx", 4),
    0xF6: ("inc", "zpx", 6),
    0xF7: ("isc", "zpx", 6),
    0xF8: ("sed", None, 2),
    0xF9: ("sbc", "aby", 4),
    0xFA: ("nop", None, 2),
    0xFB: ("isc", "aby_w", 7),
    0xFC: ("nop_read", "abx", 4),
    0xFD: ("sbc", "abx", 4),
    0xFE: ("inc", "abx_w", 7),
    0xFF: ("isc", "abx_w", 7),
}

_UNDOCUMENTED_HANDLERS = frozenset(
    (
        "slo", "rla", "sre", "rra", "sax", "lax", "dcp", "isc", "anc", "alr", "arr",
        "sbx", "usbc", "las", "jam", "sha", "shx", "shy", "tas", "ane", "lxa",
    )
)  # fmt: skip

#: The 151 opcodes MOS documents (PM Appendix D, pp. D-2 to D-5); every other
#: opcode is one of the 105 NMS describes.
DOCUMENTED: frozenset[int] = frozenset(
    opcode
    for opcode, (handler, _mode, _cycles) in OPCODES.items()
    if handler not in _UNDOCUMENTED_HANDLERS and handler != "nop_read"
) - {0x1A, 0x3A, 0x5A, 0x7A, 0xDA, 0xFA}

Entry = tuple[Callable[..., None], Callable[..., int] | None, int]


def build_table(cls: type) -> list[Entry]:
    """Resolve ``OPCODES`` into (handler, addressing-mode method, cycles), once per class.

    Built per class so that a subclass overriding a handler gets a table that
    routes to its override.
    """
    return [
        (
            getattr(cls, f"_op_{handler}"),
            None if mode is None else getattr(cls, f"_ea_{mode}"),
            cycles,
        )
        for handler, mode, cycles in (OPCODES[opcode] for opcode in range(256))
    ]
